repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-reanatax_logo_light.png
    - docs/images/nf-core-reanatax_logo_light.png
    - docs/images/nf-core-reanatax_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - docs/CONTRIBUTING.md
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-reanatax_logo_light.png
    - docs/images/nf-core-reanatax_logo_light.png
    - docs/images/nf-core-reanatax_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: BioinfoIPBLN
  name: reanatax
  description: Taxonomic profiling of the non-host fraction of public or local sequencing
    data - fetch, QC, host depletion with HISAT2, and Kraken2/Bracken classification.
  author: Jose L. Ruiz
  version: 1.0.0dev
  force: true
  outdir: /scratch/jlruiz/build/reanaTax
  skip_features:
    - igenomes
    - rocrate
    - codespaces
    - seqera_platform
  is_nfcore: false
