// FASTQ to unaligned BAM, because PathSeq will not read a FASTQ.
//
// GATK's tools take a SAM/BAM and PathSeq is no exception, so this is a format
// conversion and nothing more: no alignment happens, and every read and every
// base survives it. The read group is pinned from the sample id rather than
// left to a default, because PathSeq's own outputs carry it and an
// autogenerated one would differ between resumes.
process GATK4_FASTQTOSAM {
    tag "${meta.id}"
    label 'process_medium'

    conda "${moduleDir}/environment.yml"
    container "${workflow.containerEngine in ['singularity', 'apptainer'] && !task.ext.singularity_pull_docker_container
        ? 'https://depot.galaxyproject.org/singularity/gatk4:4.6.1.0--py310hdfd78af_0'
        : 'quay.io/biocontainers/gatk4:4.6.1.0--py310hdfd78af_0'}"

    input:
    tuple val(meta), path(reads)

    output:
    tuple val(meta), path("*.unaligned.bam"), emit: bam
    tuple val("${task.process}"), val('gatk4'), eval("gatk --version 2>&1 | sed -n 's/^The Genome Analysis Toolkit (GATK) v//p'"), emit: versions_gatk, topic: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def prefix = task.ext.prefix ?: "${meta.id}"
    def input_reads = meta.single_end ? "--FASTQ ${reads}" : "--FASTQ ${reads[0]} --FASTQ2 ${reads[1]}"
    def memory = task.memory ? "-Xmx${task.memory.toGiga()}g" : ''
    """
    gatk --java-options "${memory}" FastqToSam \\
        ${args} \\
        ${input_reads} \\
        --OUTPUT ${prefix}.unaligned.bam \\
        --SAMPLE_NAME ${prefix} \\
        --READ_GROUP_NAME ${prefix} \\
        --PLATFORM ILLUMINA
    """

    stub:
    def prefix = task.ext.prefix ?: "${meta.id}"
    """
    touch ${prefix}.unaligned.bam
    """
}
